# =============================================================
#           GLOBAL CONFIGURATION FOR GEO PHOTO TOOLKIT
#  This file defines your personal, default settings for all projects.
# =============================================================

# This section defines the default EXIF data to extract.
# The format is: <your_column_name> = "<Official_EXIF_Tag_Name>"
# Main configuration for data extraction columns
[extract.columns]
camera_make = "Make"
camera_model = "Model"
aperture = "FNumber"
iso = "ISOSpeedRatings"
shutter_speed = "ExposureTime"
altitude = "GPSAltitude"
lat = "GPSLatitude"
lon = "GPSLongitude"
datetime_original = "DateTimeOriginal"

# Configuration for KMZ file generation
[kmz.description]
template = """
    <h3>{name}</h3>
    <table border="0" cellpadding="5">
        <tr><td>Date/Time</td><td>{datetime_original}</td></tr>
        <tr><td>Coordinates</td><td>{lat}, {lon}</td></tr>
        <tr><td>Camera</td><td>{camera_make} {camera_model}</td></tr>
        <tr><td>Google Maps</td><td><a href="{maps_url}">Link</a></td></tr>
    </table>
"""

# --- NEW: Configuration for Google Cloud Services ---
# Provide the absolute path to your Google Cloud service account JSON key file.
# This is required if you use the '--ocr-engine google' or '--gcv-fallback' options.
# Example (Windows): "C:\\Users\\YourUser\\keys\\gcp-service-account.json"
# Example (Linux/macOS): "/home/youruser/keys/gcp-service-account.json"
[google_cloud]
service_account_key_path = "C:\\GitHub\\geo-photo-toolkit\\learning-free-tier-446016-1525f3494ad4.json"
